In [3]:
import torch
import numpy as np 

# View (Reshape)

In [9]:
t = np.array([[[0,1,2],
               [3,4,5]],
              
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t) #Tensor를 Float로 변형 
print(ft.shape)

torch.Size([2, 2, 3])


In [11]:
ft.view([-1,3])
print(ft.view([4,3]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


# Squeeze 

In [13]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [22]:
np.arange(12).reshape(-1,2,3).shape

(2, 2, 3)

# Unsqueeze 
- 값은 그대로고 차원을 하나 더 늘려 줌 
- reshape(-1,1)과 동일 
- axis를 ()안에 넣어줌으로써 어디에 1을 추가할 지 결정 가능 

In [28]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [31]:
print(ft.unsqueeze(1).shape)

torch.Size([3, 1])


# Type Casting 

In [33]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [34]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [35]:
torch.ByteTensor([True,False,True,True]) #ByteTensor는 True, False를 1과 0으로 반환 

tensor([1, 0, 1, 1], dtype=torch.uint8)

# Concatenate

In [53]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(x.shape,y.shape)

torch.Size([2, 2]) torch.Size([2, 2])


In [54]:
torch.cat([x,y],dim=0).shape #dim 위치로 concat 함 

torch.Size([4, 2])

# Stacking 

In [71]:
x = torch.FloatTensor([1,4]).unsqueeze(1)
y = torch.FloatTensor([2,5]).unsqueeze(1)
z = torch.FloatTensor([3,6]).unsqueeze(1)
print(x.shape,y.shape,z.shape)

torch.Size([2, 1]) torch.Size([2, 1]) torch.Size([2, 1])


In [72]:
torch.stack([x,y,z],dim=0).shape

torch.Size([3, 2, 1])

#Ones and Zeros

In [75]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x.size())
print(x)

torch.Size([2, 3])
tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [77]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#In place Operation 

In [85]:
x= torch.FloatTensor([[1,2],[3,4]])

In [86]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) #inplace = True
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
